# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.

# development:
#   adapter: async
#
# test:
#   adapter: async
#
development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true

test: *development

production: &production
  :url: redis://redistogo:057fc2bf3e2028d4587f7ba532e1ab3f@herring.redistogo.com:10198/
  :host: herring.redistogo.com
  :port: 10198
  :password: 057fc2bf3e2028d4587f7ba532e1ab3f
  :inline: true
  :timeout: 1
